# Generated by Django 3.1 on 2020-08-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customeractivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customeractivity.userdetails')),
            ],
        ),
    ]
